// Auth const
export const SET_AUTH_CONDITION = 'SET_AUTH_CONDITION';
export const SET_AJAX_LOADER = 'SET_AJAX_LOADER';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const SET_SECONDARY_NOTIFICATION = 'SET_SECONDARY_NOTIFICATION';
export const SET_MODAL = 'SET_MODAL';

// UbaDevices const
export const MAIN_PAGE_STATE = 'MAIN_PAGE_STATE';
export const SET_UBA_DEVICES = 'SET_UBA_DEVICES';
export const SET_CURRENT_UBA = 'SET_CURRENT_UBA';
export const SET_SELECTED_DEVICES = 'SET_SELECTED_DEVICES';
export const UPDATE_CURRENT_UBA = 'UPDATE_CURRENT_UBA';
export const SET_UBA_TOTAL = 'SET_UBA_TOTAL';

// TestRoutines const
export const TEST_ROUTINES_STATE = 'TEST_ROUTINES_STATE';
export const SET_TEST_ROUTINES = 'SET_TEST_ROUTINES';
export const SET_GRAPH_DATA = 'SET_GRAPH_DATA';
export const SET_TEST_TYPES = 'SET_TEST_TYPES';
export const ADD_TEST_TYPE = 'ADD_TEST_TYPE';
export const CHANGE_TEST_TYPE = 'CHANGE_TEST_TYPE';
export const FOLD_TEST_TYPE = 'FOLD_TEST_TYPE';
export const DELETE_TEST_TYPE = 'DELETE_TEST_TYPE';
export const TEST_TYPE_DATA = 'TEST_TYPE_DATA';
export const SET_TEST_DATA = 'SET_TEST_DATA'
export const ALL_TEST_DATA = 'ALL_TEST_DATA'
export const START_SAVE_ACTION = 'START_SAVE_ACTION';
export const EXISTING_TEST_PARAMETERS = 'EXISTING_TEST_PARAMETERS';
export const TEST_EDIT_PARAMETERS = 'TEST_EDIT_PARAMETERS';

// Reports const
export const SET_REPORTS = 'SET_REPORTS';
export const SET_CURRENT_REPORT = 'SET_CURRENT_REPORT';
export const UPDATE_CURRENT_REPORT = 'UPDATE_CURRENT_REPORT';
export const SET_TESTS_GRAPH = 'SET_TESTS_GRAPH';

// Settings const
export const SET_MACHINE_SETTINGS = 'SET_MACHINE_SETTINGS';
export const SET_CELL_SETTINGS = 'SET_CELL_SETTINGS';
export const SET_CURRENT_CELL = 'SET_CURRENT_CELL';
export const UPDATE_CURRENT_CELL = 'UPDATE_CURRENT_CELL';
