export default {
	common: {
		UBA_S_N: 'UBA S/N',
		NAME: 'Name',
		FILTER: 'Filter',
		FILTER_BY: 'Filter by:',
		ERROR: 'Error',
		ALL: 'All',
		ADD: 'Add',
		NEXT: 'Next',
		BACK: 'Back',
		TEST: 'Test',
		UPDATE: 'Update',
		OK: 'OK',
		DESELECT: 'Clear',
		CANCEL: 'Cancel',
		SAVE: 'Save',
		SAVE_RUN: 'Save-and-Run',
		RUN_NO_SAVE: 'Run-without-Save',
		STATUS: 'Status',
		TEST_NAME: 'Test Name',
		CHANNEL: 'Channel',
		CH_: 'Ch.',
		RUN_TIME: 'Run time',
		ACTION: 'Action',
		VOLTAGE: 'Voltage',
		CURRENT: 'Current',
		CAPACITY: 'Capacity',
		TEMPERATURE: 'Temperature',
		DATE: 'Date',
		NOT_APPLICABLE: ' ',
		LAB: 'Lab (Station)',
		TEST_CURRENTLY_RUNNING: 'Test is currently running',
		STOP: 'Stop',
		PAUSE: 'Pause',
		RESUME: 'Resume',
		CONFIRM: 'Confirm',
		VIEW_GRAPH: 'View Graph',
		AB: 'AB',
	},
	layout: {
		LOGOUT: 'Logout',
		
	},
	pages: {
		WELCOME: 'Sign in to Amicell',
		LOGIN: 'Login',
		EMAIL_ADDRESS: 'Email address',
		PASSWORD: 'Password?',
		FORGOT_PASSWORD: 'Forgot password?'
	},
	pageHeaders: {
		UBA_CONTROL_CENTER: 'UBA Control Center',
		TEST_ROUTINES: 'Test Routines',
		REPORTS: 'Reports',
		SETTINGS: 'Settings',
		USERS: 'Users',
	},
	mainPage: {
		UBA_DEVICES: 'UBA Devices',
		UBA_CONFIGURED: 'UBA Configured:',
		UBA_CONNECTED: 'UBA Connected:',
		UBA_RUNNING: 'UBA Running:',
		BATTERY_P_N_FILTER: 'Battery P.N.',
		LAB_LOCATION: 'Lab (Location)',
		READING: 'Reading',
		DETAILS: 'Graph Details',
		START_TEST: 'Start Test',
		TABLE_VIEW: 'Table View',
		CARDS_VIEW: 'Cards View',
		LAST_READING: 'Last Reading',
		runBatchTest: {
			RUN_BATCH_TEST: 'Run Batch Test',
			BATCH: 'batch',
			SERIAL_NUMBER_BATCH: 'Enter Battery Serial Number batch',
			APPROVE_BATCH_TEST: 'Please Approve Batch Test Run',
		},
		wizardZero: {
			TEST_LOCK: 'Test Lock',
			OPENED: 'Opened',
			LOCKED: 'Locked',
		},
		wizardOne: {
			ANOTHER_CHANNEL_FREE: 'Other channel is not free',
			NOT_BE_EMPTY: 'must not be empty.',
			ALREADY_EXISTS: 'already exists.',
			TEST_PLAN_NAME: 'Test Plan Name',
			TEST_CONFIGURATIONS: 'Test Configurations',
			FIND_TEST_ROUTINE: 'Find Test Routine',
			TEST_ROUTINES_FILTER: 'Test Routines Filter',
			AND_PARENTHESES: '(AND)',
			UBA_CHANNEL: 'UBA Channel',
			NOTES: 'Notes',
			CUSTOMER: 'Customer',
			WORK_ORDER_NUMBER: 'Work Order Number',
			APPROVED_BY: 'Approved By',
			CONDUCTED_BY: 'Conducted By',
			CELL_SUPPLIER: 'Cell Supplier',
			CELL_DATE: 'Cell Batch / Date Code',
			SELECT: 'Select',
			DUPLICATION_ERROR: 'Please choose existing test before proceeding.',
			MAX_PER_BATTERY: 'Max Per Battery',
			RATED_BATTERY_CAPACITY: 'Rated Battery Capacity',
		},
		wizardTwo: {
			TEST_PLAN: 'Test Plan',
			DELAY_TIME_OR_WAIT_TEMP_REQUIRED: 'At least one is mandatory: Delay Time, Wait Temp',
			MUST_BE_INTEGER: 'must be integer value.',
			MUST_BE_NUMBER: 'must be valid number.',
			MUST_BE_TIME: 'must be proper HH:mm:ss string.',
			MUST_BE_STEP: 'can be 1 to {0}.',
			TOO_LOW_TEMP: 'Warning below spec recommendations.',
			TOO_HIGH_TEMP: 'Warning above spec recommendations.',
			FIX_ALL_ERRORS: 'Please fix all errors before proceeding.',
			SOURCE: 'Source',
			MIN_TEMPERATURE: 'Min Temperature',
			MAX_TEMPERATURE: 'Max Temperature',
			MAX_TIME: 'Max Time',
			DELAY_TIME: 'Delay Time',
			CHARGE_CURRENT: 'Charge Current',
			CHARGE_PER_CELL: 'Charge per Cell',
			CHARGE_VOLTAGE: 'Charge Voltage',
			VOLTS: 'Volts',
			CUT_OFF_CURRENT: 'Cut-off Current',
			CUT_OFF_VOLTAGE: 'Cut-off Voltage - Cell',
			CUT_OFF_VOLTAGE_BATTERY: 'Cut-off Voltage - Battery',
			CHARGE_LIMIT: 'Charge Limit',
			DISCHARGE_LIMIT: 'Discharge Limit',
			IGNORE_LIMITS: 'Ignore Limits',
			WAIT_TEMPERATURE: 'Wait for temperature',
			GO_TO_STEP: 'Go to Step',
			REPEAT_STEP: 'Repeat this Step',
			TIMES: 'times',
			DISCHARGE_CURRENT: 'Discharge Current',
			INTERNAL: 'Internal',
			EXTERNAL: 'External',
			EXTERNAL_1: 'External 1',
			EXTERNAL_2: 'External 2',
			CURRENT_MA: 'Current [mA]',
			ABSOLUTE_MA: 'Absolute [mA]',
			ABSOLUTE_MAH: 'Absolute [mAh]',
			ABSOLUTE_A: 'Absolute [A]',
			ABSOLUTE_AH: 'Absolute [Ah]',
			RELATIVE: 'Relative [C]',
			POWER: 'Power [W]',
			RESISTANCE: 'Resistance [Ohm]',
			AT_LEAST_ONE: 'At least one of three checkboxes must be checked.',
			RUN: 'Run',
			TIME_FORMAT: 'HH:mm:ss',
			C_RATE: 'C-Rate',
			HIGH_CURRENT: 'High Current',
			TOO_HIGH_CAPACITY: 'Higher than Battery Nominal capacity',
			OVER_VOLTAGE: 'Pay attention: Over-Voltage per cells',
			UNDER_VOLTAGE: 'Pay attention: Under-Voltage per cells',
		}
	},
	testEditor: {
		DELAY: 'Delay',
		CHARGE: 'Charge',
		DISCHARGE: 'Discharge',
		LOOP: 'Loop',
		BATTERY_P_N: 'Battery P/N',
		CELL_P_N: 'Cell P/N',
		NO_CELLS_IN_SERIAL: 'No. Cells in Serial',
		NO_CELLS_IN_PARALLEL: 'No. Cells in Parallel',
		NEW_TEST: 'New Test',
		stepTwo: {
			CELLS_IN_SERIAL: 'Number of Cells in Serial',
			CELLS_IN_PARALLEL: 'Number of Cells in Parallel',
		}
	},
	reportsPage: {
		REPORT: 'Report',
		BATTERY_S_N: 'Battery S/N',
		SHOW_RESULT_GRAPHS: 'Show Result Graphs',
		UBA: 'UBA',
		DOWNLOAD_REPORT: 'Download Report',
		DOWNLOAD_PDF: 'Download as PDF',
		DOWNLOAD_XSLX: 'Download as XSLX',
		NO_DATA: 'No graph data available',
		LOADING: 'Loading...',
		DATE_RANGE: 'Date Range',
		DATE_RANGE_VALUES: {
			lastWeek: 'Last Week',
			lastMonth: 'Last Month',
			last6Months: 'Last 6 Months',
			lastYear: 'Last Year',
		},
		editReport: {
			EDIT_REPORT: 'Edit Report',
		}
	},
	settingsPage: {
		LABS: 'Labs (Stations)',
		uba: {
			ADD_UBA: 'Add UBA',
			EDIT_UBA: 'Edit UBA',
			PORT: 'Port',
			ADDRESS: 'Address',
			UBA_DEVICE_NO_RESPONSE: 'Oops could not find UBA device'
		},
		cell: {
			ADD_CELL: 'Add Cell',
			EDIT_CELL: 'Edit Cell',
			CHEMISTRY: 'Chemistry',
			MANUFACTURER: 'Manufacturer',
			ITEM_P_N: 'Item P/N',
			MIN_VOLT: 'Min(V)',
			MIN_VOLTAGE: 'Min Voltage',
			NOM_VOLT: 'Nom(V)',
			NOM_VOLTAGE: 'Nom Voltage',
			MAX_VOLT: 'Max(V)',
			MAX_VOLTAGE: 'Max Voltage',
			MIN_CAPAC: 'Min(mAh)',
			MIN_CAPACITY: 'Min Capacity',
			NOM_CAPAC: 'Nom(mAh)',
			NOM_CAPACITY: 'Nom Capacity',
			MIN_TEMP: 'Min(°C)',
			MAX_TEMP: 'Max(°C)',
			MIN_TEMP_2: 'Min Temp',
			MAX_TEMP_2: 'Max Temp',
			MIN_TEMPERATURE: 'Min Temperature (°C)',
			MAX_TEMPERATURE: 'Max Temperature (°C)',
			CHARGE_OPTION: 'Charge Option',
		}
	}
}
